### ISSUE TITLE
Capnp.DeserializationException : Expected a capability

### ISSUE THREAD

**Issue by teqdruid** [c80k/capnproto-dotnetcore#45]
I'm getting the following exception and stack trace:
```
  Error Message:
   Capnp.DeserializationException : Expected a capability
  Stack Trace:
     at Capnp.DeserializerState.RequireCap[T]()
   at Capnp.CapnpSerializable.FromCapability`1.Create(DeserializerState state)
   at Capnp.CapnpSerializable.Create[T](DeserializerState state)
   at CapnpGen.Value.Capnp.ICapnpSerializable.Deserialize(DeserializerState arg_) in C:\code\esi\src\core\schema\CapnpSchema.capnp.cs:line 3294
   at Capnp.CapnpSerializable.FromStruct`1.Create(DeserializerState state)
   at Capnp.CapnpSerializable.Create[T](DeserializerState state)
   at CapnpGen.Annotation.Capnp.ICapnpSerializable.Deserialize(DeserializerState arg_) in C:\code\esi\src\core\schema\CapnpSchema.capnp.cs:line 3776
   at Capnp.CapnpSerializable.FromStruct`1.Create(DeserializerState state)
   at Capnp.CapnpSerializable.Create[T](DeserializerState state)
   at CapnpGen.Field.<>c.<Capnp.ICapnpSerializable.Deserialize>b__2_0(READER _) in C:\code\esi\src\core\schema\CapnpSchema.capnp.cs:line 1106
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Capnp.ReadOnlyListExtensions.ToReadOnlyList[From,To](IReadOnlyList`1 source, Func`2 selector)
   at CapnpGen.Field.Capnp.ICapnpSerializable.Deserialize(DeserializerState arg_) in C:\code\esi\src\core\schema\CapnpSchema.capnp.cs:line 1106
   at Capnp.CapnpSerializable.FromStruct`1.Create(DeserializerState state)
   at Capnp.CapnpSerializable.Create[T](DeserializerState state)
   at CapnpGen.Node.struct.<>c.<Capnp.ICapnpSerializable.Deserialize>b__1_0(READER _) in C:\code\esi\src\core\schema\CapnpSchema.capnp.cs:line 362
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Capnp.ReadOnlyListExtensions.ToReadOnlyList[From,To](IReadOnlyList`1 source, Func`2 selector)
   at CapnpGen.Node.struct.Capnp.ICapnpSerializable.Deserialize(DeserializerState arg_) in C:\code\esi\src\core\schema\CapnpSchema.capnp.cs:line 362
   at Capnp.CapnpSerializable.FromStruct`1.Create(DeserializerState state)
   at Capnp.CapnpSerializable.Create[T](DeserializerState state)
   at CapnpGen.Node.Capnp.ICapnpSerializable.Deserialize(DeserializerState arg_) in C:\code\esi\src\core\schema\CapnpSchema.capnp.cs:line 34
   at Capnp.CapnpSerializable.FromStruct`1.Create(DeserializerState state)
   at Capnp.CapnpSerializable.Create[T](DeserializerState state)
   at Esi.Schema.EsiCapnpConvert.<>c.<ConvertFromCGRMessage>b__2_0(READER _) in C:\code\esi\src\core\schema\EsiCapnpConvert.cs:line 46
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Capnp.ReadOnlyListExtensions.ToReadOnlyList[From,To](IReadOnlyList`1 source, Func`2 selector)
   at Esi.Schema.EsiCapnpConvert.ConvertFromCGRMessage(EsiContext ctxt, Stream stream) in C:\code\esi\src\core\schema\EsiCapnpConvert.cs:line 46
   at Esi.Schema.EsiCapnpConvert.ConvertTextSchema(EsiContext ctxt, FileInfo file) in C:\code\esi\src\core\schema\EsiCapnpConvert.cs:line 74
   at Esi.Core.Tests.CapnpTest.ReadSchema(String resource) in C:\code\esi\src\core\tests\CapnpTest.cs:line 20
   at Esi.Core.Tests.Stress1UnitTest.ReadStress1a() in C:\code\esi\src\core\tests\stress_tests\Stress1.cs:line 18
```

When I try to deserialize the following capnp binary file:
[stress1.capnp.CodeGeneratorRequest.bin.txt](https://github.com/c80k/capnproto-dotnetcore/files/4300205/stress1.capnp.CodeGeneratorRequest.bin.txt). (The txt extension is to get around GH file type limits.) Here is the textual version of it: 
[stress1.capnp.CodeGeneratorRequest.txt](https://github.com/c80k/capnproto-dotnetcore/files/4300239/stress1.capnp.CodeGeneratorRequest.txt)

I am trying to drive it with the following code:
```
            var frame = Framing.ReadSegments(stream);
            var deserializer = DeserializerState.CreateRoot(frame);
            var reader = CodeGeneratorRequest.READER.create(deserializer);
            var cgr = new CodeGeneratorRequest();
            cgr.Nodes = reader.Nodes.ToReadOnlyList(_ => CapnpSerializable.Create<CapnpGen.Node>(_));
            cgr.RequestedFiles = reader.RequestedFiles.ToReadOnlyList(_ => CapnpSerializable.Create<CapnpGen.CodeGeneratorRequest.RequestedFile>(_));
            cgr.CapnpVersion = CapnpSerializable.Create<CapnpGen.CapnpVersion>(reader.CapnpVersion);
            cgr.applyDefaults();
```

and the attached schema. It's the capnp codegen schema -- I'm trying to write a capnp codegen in C#.
[CapnpSchema.capnp.txt](https://github.com/c80k/capnproto-dotnetcore/files/4300209/CapnpSchema.capnp.txt)

This is with netstandard2.1 and the following versions:
```
    <PackageReference Include="Capnp.Net.Runtime" Version="1.2.189" />
    <PackageReference Include="CapnpC.CSharp.MsBuild.Generation" Version="1.2.138" />
```
(It also repros with runtime version 1.2.138.)

Can you take a look and tell me if I'm doing something wrong? Is this a bug in the Capnp.Net code? 

If it's useful, I can supply the schema which I'm running through capnp to get the CodeGeneratorRequest.

**Comment by teqdruid** [comment]
BTW, CapnpC.CSharp.MsBuild.Generation 1.2.189 doesn't seem to be on nuget.org.

**Comment by c80k** [comment]
Thanks for reporting. It's a bug in the code generated from CapnpC.CSharp.MsBuild.Generation. In your use case it should be perfectly fine to go on with the reader from line 3. It provides everything you need for driving a your codegen. The generator inside CapnpC.CSharp.MsBuild.Generation uses it, too.
I did not publish CapnpC.CSharp.MsBuild.Generation 1.2.189 because it does not contain any change compared to version 1.2.138, so that's fine.

**Comment by teqdruid** [comment]
Yep. It works through the reader

Thanks!

**Comment by c80k** [comment]
Version 1.3.118 should fix this issue. I'll close it now.
